# Validate with curl --data-binary @.codecov.yml https://codecov.io/validate
codecov:
  token: 7259f8b2-7cfe-476f-9278-b9ec3d711006
  archive:
    uploads: yes

coverage:
  precision: 2
  round: down
  range: 50...100
  status:
    project:
      default:
        # coverage may fall by <1.0% and still be considered "passing"
        threshold: 1.0%
    patch:
      default:
        # coverage may fall by <1.0% and still be considered "passing"
        threshold: 1.0%

comment:
  layout: "header, diff, changes"